# Generated by Django 2.1.3 on 2019-01-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20190121_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrzeug',
            name='volumen',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lieferungen',
            name='id_fahrzeug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_fahrzeug', to='collect.Fahrzeug'),
            preserve_default=False,
        ),
    ]
