# Generated by Django 3.0.6 on 2020-05-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_auto_20190126_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieferungen',
            name='datum_bis',
        ),
    ]
