# Generated by Django 2.1.3 on 2019-01-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkte',
            name='datum_untersuchung',
            field=models.DateField(),
        ),
    ]
