# Generated by Django 2.1.3 on 2019-01-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20190111_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieferungen',
            name='id_abgeber',
        ),
        migrations.AddField(
            model_name='lieferungen',
            name='id_abgeber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_abgeber', to='collect.Kunde'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lieferungen',
            name='id_aufnehmer',
        ),
        migrations.AddField(
            model_name='lieferungen',
            name='id_aufnehmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_aufnehmer', to='collect.Kunde'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lieferungen',
            name='id_beförderer',
        ),
        migrations.AddField(
            model_name='lieferungen',
            name='id_beförderer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_beförderer', to='collect.Kunde'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lieferungen',
            name='id_fahrer',
        ),
        migrations.AddField(
            model_name='lieferungen',
            name='id_fahrer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_fahrer', to='collect.Fahrer'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lieferungen',
            name='id_produkt',
        ),
        migrations.AddField(
            model_name='lieferungen',
            name='id_produkt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_produkte', to='collect.Produkte'),
            preserve_default=False,
        ),
    ]
